apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: servicenow-databricks-demo

resources:
  - ../../namespace.yaml
  - ../../configmap.yaml
  - ../../proxy-deployment.yaml
  - ../../servicenow-deployment.yaml
  - ../../databricks-deployment.yaml

patches:
  - path: configmap-patch.yaml
  - path: databricks-deployment-patch.yaml

commonLabels:
  demo: servicenow-databricks
  managed-by: suse-ai-up
